title: interstellagram
author: Jonna Nolan
email: interstellagram@ggmail.com
description: >-
  Hello. I'm Jonna Nolan, a film critic exploring image, memory, and time through science fiction and arthouse cinema.

url: "https://interstellagram.github.io"
baseurl: ""
show_excerpts: true

sass:
  sass_dir: _sass

plainwhite:
  name: interstellagram
  tagline: Film Critic Jonna Nolan
  date_format: "%Y-%m-%d"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/portfolio.png"
  html_lang: "en"
  condensed_mobile:
    - page
    - post

  social_links:
    github: interstellagram
    email: interstellagram@ggmail.com

plugins:
  - jekyll-seo-tag